### ISSUE TITLE
TestImageDataset Class Little doubt

### ISSUE THREAD

**Issue by BaseBlank** [Lornatang/DRRN-PyTorch#2]
Hello, thank you very much for sharing your excellent work on DRRN model. When I study related code, found that some codes were not too robust, and hope to communicate.

First of all, in the process of obtaining LR image from HR image, the shape of HR is [H,W,C], and there are two cases:
dataset.py: 105~106 lines
`lr_image = imgproc.imresize(lr_image, 1 / self.upscale_factor)`
`lr_image = imgproc.imresize(lr_image, self.upscale_factor)`
1. If H % upscale_factor=0 and W % upscale_factor=0, the shape of LR image is also [H,W,C], which is exactly the same as that of HR.
2. If the H % upscale_factor != 0, W % upscale_factor != 0, then the shape of LR image may be [H+-1,W+-1,C] or [H+-2,W+-2,C].
If HR.shape != LR.Shape, an error occurs when PSNR is calculated.

In TrainValidImageDataset Class, using random_crop function to crop images can ensure that the dimensions of HR and LR images are exactly the same, and no error will be reported when calculating PSNR; 
However, in TestImageDataset class, the relevant crop function is not used, which cannot guarantee that the calculation of PSNR will not result in errors. 

Since the test set image(Set5/GTmod12) sizes used in this code are [504,504], [288,288], [252,252], [276,276], [228,336], all of which are exactly integer multiples of upscale_factor= 2,3,4 and can be divisible, The shape of HR and LR image will be exactly the same.

However, if change to another test set, may get H % upscale_factor != 0, W % upscale_factor !=0, an error will be reported when calculating PSNR.

**Comment by Lornatang** [comment]
I see

**Comment by Lornatang** [comment]
I will modify this code according to the latest code architecture, please wait

**Comment by Lornatang** [comment]
The test data set is considered to have been preprocessed, so there is no crop
